const constants =  {
    TOGGLE_LOGIN: "TOGGLE_LOGIN",
    CHANGE_EMAIL: "CHANGE_EMAIL",
    CHANGE_WALLET_ID: "CHANGE_WALLET_ID",
    CHANGE_SURPLUS: "CHANGE_SURPLUS",
    GET_ALL_EXCHANGE_LIST: "GET_ALL_EXCHANGE_LIST",
    IS_SIGN_UP_START: "IS_SIGN_UP_START",
    IS_SIGN_UP_DONE: "IS_SIGN_UP_DONE",
    IS_EXCHANGE_START: "IS_EXCHANGE_START",
    IS_EXCHANGE_DONE: "IS_EXCHANGE_DONE",
    IS_SIGN_IN_START: "IS_SIGN_IN_START",
    IS_SIGN_IN_DONE: "IS_SIGN_IN_DONE",
    EXCHANGE_TO_SUCCESSFUL: "EXCHANGE_TO_SUCCESSFUL",
    EXCHANGE_TO_FAIL: "EXCHANGE_TO_FAIL",
    EXCHANGE_TO_STATUS_RESET: "EXCHANGE_TO_STATUS_RESET",
    GET_EXCHANGES_OF_USER: "GET_EXCHANGES_OF_USER"
};

export default constants;
